service: api

provider:
  name: google
  stage: ${opt:stage, 'production'}
  runtime: python37
  region: us-central1
  project: ${opt:id, 'japan-grid-carbon-api'}
  environment:
    STAGE: ${opt:stage, self:provider.stage, 'production'}
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/japan-grid-carbon-service-key-${opt:stage, self:provider.stage, 'production'}.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - test_*

functions:
  api:
    name: api
    handler: api
    memorySize: 128
    timeout: 120s
    events:
      - http: path
  scrapers:
    name: scrapers
    handler: scrapers
    memorySize: 256
    timeout: 120s
    events:
      - http: path
