# Generated by Django 3.0.2 on 2020-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_grid_carbon_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tepcoenergydata',
            name='carbon_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
