version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - STAGE=stagings
      - GOOGLE_APPLICATION_CREDENTIALS=.gcloud/japan-grid-carbon-service-key-staging.json
